In [1]:
import warnings
warnings.filterwarnings("ignore")

import os
import sys
import time
import json
import numpy as np
import pandas as pd
import geopandas as gpd
import pickle as pkl
import networkx as nx
import matplotlib.pyplot as plt
import networkx as nx

import src
from src.reload import deep_reload

In [6]:
def normalized_information_centrality(graph, weight = None):

    a = nx.to_numpy_array(graph, weight = weight)
    a /= a.sum()
    d = np.diag([r.sum() for r in a])
    b =  d - a + 1
    
    c = np.linalg.inv(b)
    
    n = graph.number_of_nodes()
    
    ic = 1 / (np.diag(c) + (np.diag(c).sum() - 2 * c.sum(axis = 0)) / n)

    node_ids = list(graph.nodes)
    
    return {node_ids[idx]: ic[idx] for idx in range(n)}

In [7]:
edges = [
    ('A', 'F', 2),
    ('B', 'G', 2),
    ('C', 'F', 2),
    ('D', 'F', 1),
    ('E', 'H', 2),
    ('E', 'I', 3),
    ('F', 'J', 3),
    ('G', 'J', 2),
    ('H', 'J', 3),
    ('I', 'J', 2),
    ('J', 'K', 3),
    ('K', 'L', 3),
    ('K', 'N', 3),
    ('L', 'O', 2),
    ('L', 'P', 2),
    ('L', 'M', 1),
    ('N', 'R', 2),
    ('N', 'Q', 2),
]

g = nx.Graph()
g.add_weighted_edges_from(edges)
ic_1 = normalized_information_centrality(g, weight = 'weight')

g = nx.Graph()
g.add_weighted_edges_from(edges + [('I', 'N', 6)])
ic_2 = normalized_information_centrality(g, weight = 'weight')

g = nx.Graph()
g.add_weighted_edges_from(edges + [('I', 'K', 4)])
ic_3 = normalized_information_centrality(g, weight = 'weight')

g = nx.Graph()
g.add_weighted_edges_from(edges + [('J', 'L', 5)])
ic_4 = normalized_information_centrality(g, weight = 'weight')

print('\\hline Node & Baseline & (I, N) & (I, K) & (J, L) \\\\')
for key in ic_1.keys():
    print(f'\\hline {key} & {ic_1[key]:.4f} & {ic_2[key]:.4f} & {ic_3[key]:.4f} & {ic_4[key]:.4f} \\\\')
print(f'\\hline Sum & {sum(ic_1.values()):.4f} & {sum(ic_2.values()):.4f} & {sum(ic_3.values()):.4f} & {sum(ic_4.values()):.4f} \\\\')
# print(f'\\hline Gini & {gini(list(ic_1.values())):.3f} & {gini(list(ic_2.values())):.3f} & {gini(list(ic_3.values())):.3f} & {gini(list(ic_4.values())):.3f} \\\\')
print('\\hline')

\hline Node & Baseline & (I, N) & (I, K) & (J, L) \\
\hline A & 0.0089 & 0.0083 & 0.0085 & 0.0088 \\
\hline F & 0.0131 & 0.0127 & 0.0128 & 0.0137 \\
\hline B & 0.0078 & 0.0072 & 0.0074 & 0.0076 \\
\hline G & 0.0108 & 0.0102 & 0.0104 & 0.0109 \\
\hline C & 0.0089 & 0.0083 & 0.0085 & 0.0088 \\
\hline D & 0.0068 & 0.0062 & 0.0064 & 0.0065 \\
\hline E & 0.0114 & 0.0124 & 0.0126 & 0.0117 \\
\hline H & 0.0128 & 0.0129 & 0.0129 & 0.0133 \\
\hline I & 0.0120 & 0.0146 & 0.0149 & 0.0123 \\
\hline J & 0.0162 & 0.0162 & 0.0161 & 0.0177 \\
\hline K & 0.0155 & 0.0153 & 0.0162 & 0.0157 \\
\hline L & 0.0126 & 0.0122 & 0.0128 & 0.0164 \\
\hline N & 0.0121 & 0.0147 & 0.0123 & 0.0119 \\
\hline O & 0.0087 & 0.0081 & 0.0085 & 0.0099 \\
\hline P & 0.0087 & 0.0081 & 0.0085 & 0.0099 \\
\hline M & 0.0066 & 0.0061 & 0.0064 & 0.0071 \\
\hline R & 0.0085 & 0.0092 & 0.0083 & 0.0081 \\
\hline Q & 0.0085 & 0.0092 & 0.0083 & 0.0081 \\
\hline Sum & 0.1899 & 0.1920 & 0.1917 & 0.1984 \\
\hline


In [82]:
deep_reload(src)
from src.utilities import gini

edges = [
    ('A', 'F', 2),
    ('B', 'G', 2),
    ('C', 'F', 2),
    ('D', 'F', 1),
    ('E', 'H', 2),
    ('E', 'I', 3),
    ('F', 'J', 3),
    ('G', 'J', 2),
    ('H', 'J', 3),
    ('I', 'J', 2),
    ('J', 'K', 3),
    ('K', 'L', 3),
    ('K', 'N', 3),
    ('L', 'O', 2),
    ('L', 'P', 2),
    ('L', 'M', 1),
    ('N', 'R', 2),
    ('N', 'Q', 2),
]

g = nx.Graph()
g.add_weighted_edges_from(edges)
ic_1 = nx.betweenness_centrality(g, weight = 'weight')

g = nx.Graph()
g.add_weighted_edges_from(edges + [('I', 'N', 6)])
ic_2 = nx.betweenness_centrality(g, weight = 'weight')

g = nx.Graph()
g.add_weighted_edges_from(edges + [('I', 'K', 4)])
ic_3 = nx.betweenness_centrality(g, weight = 'weight')

g = nx.Graph()
g.add_weighted_edges_from(edges + [('J', 'L', 5)])
ic_4 = nx.betweenness_centrality(g, weight = 'weight')

print('\\hline Node & Baseline & (I, N) & (I, K) & (J, L) \\\\')
for key in ic_1.keys():
    print(f'\\hline {key} & {ic_1[key]:.3f} & {ic_2[key]:.3f} & {ic_3[key]:.3f} & {ic_4[key]:.3f} \\\\')
print(f'\\hline Sum & {sum(ic_1.values()):.3f} & {sum(ic_2.values()):.3f} & {sum(ic_3.values()):.3f} & {sum(ic_4.values()):.3f} \\\\')
print(f'\\hline Gini & {gini(list(ic_1.values())):.3f} & {gini(list(ic_2.values())):.3f} & {gini(list(ic_3.values())):.3f} & {gini(list(ic_4.values())):.3f} \\\\')
print('\\hline')

\hline Node & Baseline & (I, N) & (I, K) & (J, L) \\
\hline A & 0.000 & 0.000 & 0.000 & 0.000 \\
\hline F & 0.331 & 0.331 & 0.331 & 0.331 \\
\hline B & 0.000 & 0.000 & 0.000 & 0.000 \\
\hline G & 0.118 & 0.118 & 0.118 & 0.118 \\
\hline C & 0.000 & 0.000 & 0.000 & 0.000 \\
\hline D & 0.000 & 0.000 & 0.000 & 0.000 \\
\hline E & 0.004 & 0.004 & 0.004 & 0.004 \\
\hline H & 0.055 & 0.044 & 0.026 & 0.055 \\
\hline I & 0.055 & 0.066 & 0.085 & 0.055 \\
\hline J & 0.724 & 0.680 & 0.607 & 0.724 \\
\hline K & 0.603 & 0.559 & 0.603 & 0.309 \\
\hline L & 0.331 & 0.331 & 0.331 & 0.331 \\
\hline N & 0.228 & 0.228 & 0.228 & 0.228 \\
\hline O & 0.000 & 0.000 & 0.000 & 0.000 \\
\hline P & 0.000 & 0.000 & 0.000 & 0.000 \\
\hline M & 0.000 & 0.000 & 0.000 & 0.000 \\
\hline R & 0.000 & 0.000 & 0.000 & 0.000 \\
\hline Q & 0.000 & 0.000 & 0.000 & 0.000 \\
\hline Sum & 2.449 & 2.360 & 2.331 & 2.154 \\
\hline Gini & 0.740 & 0.735 & 0.731 & 0.730 \\
\hline


In [146]:
edges = [
    ('A', 'F', 2),
    ('B', 'G', 2),
    ('C', 'F', 2),
    ('D', 'F', 1),
    ('E', 'H', 2),
    ('E', 'I', 3),
    ('F', 'J', 3),
    ('G', 'J', 2),
    ('H', 'J', 3),
    ('I', 'J', 2),
    ('J', 'K', 3),
    ('K', 'L', 3),
    ('K', 'N', 3),
    ('L', 'O', 2),
    ('L', 'P', 2),
    ('L', 'M', 1),
    ('N', 'R', 2),
    ('N', 'Q', 2),
    # ('F', 'G', 1),
    # # ('G', 'H', 1),
    # ('G', 'I', 1),
    # ('N', 'M', 1),
]

g = nx.Graph()
g.add_weighted_edges_from(edges)
ic_1 = nx.betweenness_centrality(g, weight = 'weight')

g = nx.Graph()
g.add_weighted_edges_from(edges + [('I', 'N', 6)])
ic_2 = nx.betweenness_centrality(g, weight = 'weight')
15
g = nx.Graph()
g.add_weighted_edges_from(edges + [('I', 'K', 4)])
ic_3 = nx.betweenness_centrality(g, weight = 'weight')

g = nx.Graph()
g.add_weighted_edges_from(edges + [('J', 'L', 5)])
ic_4 = nx.betweenness_centrality(g, weight = 'weight')

print('\\hline Node & Baseline & (I, N) & (I, K) & (J, L) \\\\')
for key in ic_1.keys():
    print(f'\\hline {key} & {ic_1[key]:.3f} & {ic_2[key]:.3f} & {ic_3[key]:.3f} & {ic_4[key]:.3f} \\\\')
print(f'\\hline Sum & {sum(ic_1.values()):.3f} & {sum(ic_2.values()):.3f} & {sum(ic_3.values()):.3f} & {sum(ic_4.values()):.3f} \\\\')
print('\\hline')

\hline Node & Baseline & (I, N) & (I, K) & (J, L) \\
\hline A & 0.000 & 0.000 & 0.000 & 0.000 \\
\hline F & 0.331 & 0.331 & 0.331 & 0.331 \\
\hline B & 0.000 & 0.000 & 0.000 & 0.000 \\
\hline G & 0.118 & 0.118 & 0.118 & 0.118 \\
\hline C & 0.000 & 0.000 & 0.000 & 0.000 \\
\hline D & 0.000 & 0.000 & 0.000 & 0.000 \\
\hline E & 0.004 & 0.004 & 0.004 & 0.004 \\
\hline H & 0.055 & 0.044 & 0.026 & 0.055 \\
\hline I & 0.055 & 0.066 & 0.085 & 0.055 \\
\hline J & 0.724 & 0.680 & 0.607 & 0.724 \\
\hline K & 0.603 & 0.559 & 0.603 & 0.309 \\
\hline L & 0.331 & 0.331 & 0.331 & 0.331 \\
\hline N & 0.228 & 0.228 & 0.228 & 0.228 \\
\hline O & 0.000 & 0.000 & 0.000 & 0.000 \\
\hline P & 0.000 & 0.000 & 0.000 & 0.000 \\
\hline M & 0.000 & 0.000 & 0.000 & 0.000 \\
\hline R & 0.000 & 0.000 & 0.000 & 0.000 \\
\hline Q & 0.000 & 0.000 & 0.000 & 0.000 \\
\hline Sum & 2.449 & 2.360 & 2.331 & 2.154 \\
\hline


In [30]:
ic = nx.information_centrality(g, weight = 'weight')
ic, sum(list(ic.values()))

({'A': 0.0441776166742184,
  'F': 0.0683251576734408,
  'B': 0.03801910703840904,
  'G': 0.05463715326421966,
  'C': 0.04417761667421842,
  'D': 0.032641446267157696,
  'E': 0.05835702528804431,
  'H': 0.06650750341064124,
  'I': 0.06171862636493118,
  'J': 0.08847549909255899,
  'K': 0.0785024154589372,
  'L': 0.08179530201342285,
  'N': 0.059742647058823525,
  'O': 0.04944219066937119,
  'P': 0.04944219066937119,
  'M': 0.035428779069767435,
  'R': 0.0404228855721393,
  'Q': 0.04042288557213931},
 0.992236047831812)

In [70]:
q = np.array([
    [0, 1, 0],
    [0, .1, .9],
    [.6, .4, 0],
    ])

s = np.array([[.5, .2, .3]])

s @ q

array([[0.18, 0.64, 0.18]])

In [164]:
a = np.array([1])
b = np.array([.5] * 2)
c = np.array([1/6] * 6)
(a * np.log2(1 / a)).sum(), (b * np.log2(1 / b)).sum(), (c * np.log2(1 / c)).sum()

(0.0, 1.0, 2.584962500721156)

In [169]:
a = np.array([
    [4, 0, 1, 0, 0],
    [0, 4, 0, 1, 0],
    [1, 0, 3, 0, 1],
    [0, 1, 0, 3, 1],
    [0, 0, 1, 1, 3],
])

np.linalg.det(a)

array([[16,  0,  1,  0,  0],
       [ 0, 16,  0,  1,  0],
       [ 1,  0,  9,  0,  1],
       [ 0,  1,  0,  9,  1],
       [ 0,  0,  1,  1,  9]])

In [174]:
def transposeMatrix(m):
    return list(map(list,zip(*m)))

def getMatrixMinor(m,i,j):
    return [row[:j] + row[j+1:] for row in (m[:i]+m[i+1:])]

def getMatrixDeternminant(m):
    #base case for 2x2 matrix
    if len(m) == 2:
        return m[0][0]*m[1][1]-m[0][1]*m[1][0]

    determinant = 0
    for c in range(len(m)):
        determinant += ((-1)**c)*m[0][c]*getMatrixDeternminant(getMatrixMinor(m,0,c))
    return determinant

def getMatrixInverse(m):
    determinant = getMatrixDeternminant(m)
    #special case for 2x2 matrix:
    if len(m) == 2:
        return [[m[1][1]/determinant, -1*m[0][1]/determinant],
                [-1*m[1][0]/determinant, m[0][0]/determinant]]

    #find matrix of cofactors
    cofactors = []
    for r in range(len(m)):
        cofactorRow = []
        for c in range(len(m)):
            minor = getMatrixMinor(m,r,c)
            cofactorRow.append(((-1)**(r+c)) * getMatrixDeternminant(minor))
        cofactors.append(cofactorRow)
    cofactors = transposeMatrix(cofactors)
    for r in range(len(cofactors)):
        for c in range(len(cofactors)):
            cofactors[r][c] = cofactors[r][c]/determinant
    return cofactors


a = [
    [4, 0, 1, 0, 0],
    [0, 4, 0, 1, 0],
    [1, 0, 3, 0, 1],
    [0, 1, 0, 3, 1],
    [0, 0, 1, 1, 3],
]

np.array(getMatrixInverse(a)) * 275

array([[ 76.,   1., -29.,  -4.,  11.],
       [  1.,  76.,  -4., -29.,  11.],
       [-29.,  -4., 116.,  16., -44.],
       [ -4., -29.,  16., 116., -44.],
       [ 11.,  11., -44., -44., 121.]])